name: Create release
on:
  workflow_dispatch:
  schedule: 
    - cron: '11 02 * * *'
defaults:
  run: { shell: bash }

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      out: ${{ toJson(steps) }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with: {python-version: '3.8'}
    - name: Create release
      id: step1
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      run: |
        pip install -Uq ghapi
        python .github/scripts/prebuild.py

  build:
    needs: [prebuild]
    strategy:
      fail-fast: false
      matrix: { os: [macos, ubuntu, windows] }
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with: {python-version: '3.8'}
    - name: Upload artifacts
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
        CONTEXT_NEEDS: ${{ toJson(needs) }}
      run: |
        pip install -Uq ghapi
        python .github/scripts/build.py
